Namespace(net='oneprompt', baseline='unet', seg_net='transunet', mod='one_adpt', exp_name='basic_exp', type='map', vis=None, reverse=False, pretrain=False, val_freq=100, gpu=True, gpu_device=0, sim_gpu=0, epoch_ini=1, image_size=1024, out_size=256, patch_size=4, dim=256, depth=1, heads=16, mlp_dim=1024, w=4, b=4, s=True, warm=1, lr=0.0001, uinch=1, imp_lr=0.0003, weights=0, base_weights=0, sim_weights=0, distributed='none', dataset='oneprompt', one_ckpt=None, thd=False, chunk=1, num_sample=4, roi_size=96, evl_chunk=None, data_path='/fred/oz345/khoa/one-prompt/data/ISIC', path_helper={'prefix': 'logs/basic_exp_2024_11_04_18_38_13', 'ckpt_path': 'logs/basic_exp_2024_11_04_18_38_13/Model', 'log_path': 'logs/basic_exp_2024_11_04_18_38_13/Log', 'sample_path': 'logs/basic_exp_2024_11_04_18_38_13/Samples'})
Loading dataset:   0%|          | 0/24 [00:00<?, ?it/s]Loading dataset:   4%|▍         | 1/24 [00:00<00:04,  5.07it/s]Loading dataset:  17%|█▋        | 4/24 [00:00<00:04,  4.84it/s]Loading dataset:  21%|██        | 5/24 [00:01<00:05,  3.43it/s]Loading dataset:  25%|██▌       | 6/24 [00:01<00:05,  3.48it/s]Loading dataset:  33%|███▎      | 8/24 [00:01<00:02,  5.34it/s]Loading dataset:  38%|███▊      | 9/24 [00:02<00:03,  4.68it/s]Loading dataset:  42%|████▏     | 10/24 [00:02<00:02,  5.01it/s]Loading dataset:  50%|█████     | 12/24 [00:02<00:01,  7.33it/s]Loading dataset:  58%|█████▊    | 14/24 [00:02<00:01,  8.61it/s]Loading dataset:  67%|██████▋   | 16/24 [00:02<00:01,  6.05it/s]Loading dataset:  75%|███████▌  | 18/24 [00:03<00:00,  7.52it/s]Loading dataset:  83%|████████▎ | 20/24 [00:03<00:00,  5.72it/s]Loading dataset:  92%|█████████▏| 22/24 [00:03<00:00,  6.77it/s]Loading dataset: 100%|██████████| 24/24 [00:03<00:00,  8.08it/s]Loading dataset: 100%|██████████| 24/24 [00:03<00:00,  6.07it/s]
Loading dataset:   0%|          | 0/2 [00:00<?, ?it/s]Loading dataset:  50%|█████     | 1/2 [00:30<00:30, 30.38s/it]Loading dataset: 100%|██████████| 2/2 [00:38<00:00, 17.35s/it]Loading dataset: 100%|██████████| 2/2 [00:38<00:00, 19.30s/it]
Epoch 0:   0%|          | 0/180 [00:00<?, ?img/s]Exception in thread Thread-11 (enqueue_values):
Traceback (most recent call last):
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/spatial/dictionary.py", line 1592, in __call__
    d[key] = self.flipper(d[key], lazy=lazy_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/spatial/array.py", line 698, in __call__
    return flip(img, self.spatial_axis, lazy=lazy_, transform_info=self.get_transform_info())  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/spatial/functional.py", line 257, in flip
    xform[sp, sp], xform[sp, -1] = xform[sp, sp] * -1, sp_size[sp] - 1
                                                       ~~~~~~~^^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
             ^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
           ^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.spatial.dictionary.RandFlipd object at 0x145c6c389550>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/data/thread_buffer.py", line 49, in enqueue_values
    for src_val in self.src:
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/data/dataset.py", line 112, in __getitem__
    return self._transform(index)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/data/dataset.py", line 910, in _transform
    return super()._transform(index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/data/dataset.py", line 98, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x145c6e0bea10>
Epoch 0:   0%|          | 0/180 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "/fred/oz345/khoa/one-prompt/train.py", line 82, in <module>
    loss = function.train_one(args, net, optimizer, nice_train_loader, epoch, writer, vis = args.vis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz345/khoa/one-prompt/function.py", line 176, in train_one
    return loss
           ^^^^
UnboundLocalError: cannot access local variable 'loss' where it is not associated with a value
